name: Build, Test and Publish

on:
    pull_request: # different type of PRs that listeners trigger the workflow
        types: [opened, synchronize]
    push:
        branches:
            - main # main should get a push once a pull request is merged to the /staging branch. Post-merge
    workflow_dispatch: # allows us to manually trigger the workflow from the Actions tab in GitHub. This is useful for testing and debugging the workflow.

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: |
          /bin/bash run.sh install
          /bin/bash run.sh build
          /bin/bash run.sh publish:test
        env:
          TEST_PYPI_TOKEN: ${{secrets.TEST_PYPI_TOKEN}}# we will use a github expression
