name: Build, Test and Publish

on:
    pull_request: # different type of PRs that listeners trigger the workflow
        types: [opened, synchronize]
    push:
        branches:
            - main # main should get a push once a pull request is merged to the /staging branch. Post-merge

jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          /bin/bash run.sh install
          /bin/bash run.sh build
          /bin/bash run.sh publish:test
        env:
          TEST_PYPI_API_TOKEN: ${{secrets.}}# we will use a github expression
